export const SALA_ID = "anil-locke-2026"

export const JUGADORES = [
  { id: 1, name: "Rubaso" },
  { id: 2, name: "Ferrox" },
  { id: 3, name: "Zigurath" },
  { id: 4, name: "Solcius" },
  { id: 5, name: "Ruina" },
  { id: 6, name: "Tencachy" },
  { id: 7, name: "GoblinPeke" },
  { id: 8, name: "Davvo" },
]

export const ESTADOS = [
  { id: "PENDIENTE", label: "PENDIENTE", color: "bg-slate-500" },
  { id: "VIVO", label: "VIVO", color: "bg-sky-500" },
  { id: "MUERTO", label: "MUERTO", color: "bg-fuchsia-500" },
  { id: "ESCAPADO", label: "ESCAPADO", color: "bg-amber-500" },
]

export const RUTAS_ANIL = [
    "Pueblo Paleta",
    "Ciudad Verde",
    "Ciudad Plateada",
    "Ciudad Celeste",
    "Ciudad Carmin",
    "Pueblo Lavanda",
    "Ciudad Azulona",
    "Ciudad Azafran",
    "Ciudad Fucsia",
    "Isla Canela",
    "Ruta 1",
      "Ruta 2",
      "Ruta 3",
      "Ruta 4",
      "Ruta 5",
      "Ruta 6",
      "Ruta 7",
      "Ruta 8",
      "Ruta 9",
      "Ruta 10",
      "Ruta 11",
      "Ruta 12",
      "Ruta 13",
      "Ruta 14",
      "Ruta 15",
      "Ruta 16",
      "Ruta 17",
      "Ruta 18",
      "Ruta 19",
      "Ruta 20",
      "Ruta 21",
      "Ruta 22",
      "Ruta 23",
      "Ruta 24",
      "Ruta 25",
      "Bosque Verde",
      "Monte Moon",
      "Tunel Roca",
      "Cueva Diglett",
      "Torre Pokemon",
      "Zona Safari",
      "Central Energia",
      "Mansion Pokemon",
      "Islas Espuma",
      "Calle Victoria",
      "Cueva Celeste",
      "Isla Uno",
      "Camino Candela",
      "Monte Ascuas",
      "Isla Dos",
      "Cabo Brisca",
      "Isla Tres",
      "Puerto Isla Tres",
      "Puente Vinculo",
      "Bosque Baya",
      "Isla Cuatro",
      "Cueva Glaciada",
      "Isla Cinco",
      "Via Marina",
      "Prado Isla Cinco",
      "Cueva Perdida",
      "Isla Seis",
      "Ruta Verde",
      "Valle Ruinas",
      "Bosque Punteado",
      "Isla Siete",
      "Torre Desafio",
      "Canion Sepalo",
      "Ruinas Siete"
]